#!/bin/bash

# Остановка и удаление старой версии Xray
systemctl stop xray
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ remove

# Установка зависимостей
apt update
apt install curl -y

# Установка Xray
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install

# Создание конфигурации
cat << EOF > /usr/local/etc/xray/config.json
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "c8bb6cd4-ce45-4fea-8d1f-02c18f06e9ac",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "vk.com:443",
          "xver": 0,
          "serverNames": [
            "vk.com",
            "www.vk.com"
          ],
          "privateKey": "yNo7eVCe9W3mUIErCHgPsBnb0j3VX2VZ5J5M132OdbE",
          "shortIds": [
            "aabbccdd"
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ]
}
EOF

# Включение и запуск службы
systemctl enable xray
systemctl restart xray

# Получение IP-адреса сервера
IP=$(curl -4 -s icanhazip.com)

# Вывод ссылки для подключения
echo ""
echo "Ссылка для подключения:"
echo "vless://c8bb6cd4-ce45-4fea-8d1f-02c18f06e9ac@$IP:443?security=reality&sni=vk.com&fp=chrome&pbk=Ll0cRGQTHdp8yTeebe4B27O2s5SWsXWvan_eTS2rP1k&sid=aabbccdd&type=tcp&flow=xtls-rprx-vision#vless-server"
echo ""
